language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt

before_script:
  - python3 manage.py collectstatic --noinput
  - python3 manage.py migrate

script:
  - python manage.py test apps

deploy:
  provider: heroku
  api_key:
    secure: "Put your secret key here!"
  app: Vibely
  on:
    repo: quimpm/web_project
    branch: master


